crm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView, 
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.urls import path, include
from leads.views import LandingPageView, SignupView, DashboardView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('leads/',  include('leads.urls', namespace="leads")),
    path('agents/',  include('agents.urls', namespace="agents")),
    path('parties/',  include('parties.urls', namespace="parties")),
    path('tasks/',  include('tasks.urls', namespace="tasks")),
    path('kpis/',  include('kpis.urls', namespace="kpis")),
    path('signup/', SignupView.as_view(), name='signup'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leads/urls.py
from django.urls import path
from .views import (
    LeadListView, LeadDetailView, LeadCreateView, LeadUpdateView, LeadDeleteView,
    AssignAgentView, CategoryListView, CategoryDetailView, LeadCategoryUpdateView,
    CategoryCreateView, CategoryUpdateView, CategoryDeleteView, LeadJsonView, 
    FollowUpCreateView, FollowUpUpdateView, FollowUpDeleteView, OpportunityListView, OpportunityConvertView,
    OpportunityUpdateView,OpportunityDetailView,OppFollowUpCreateView,OppFollowUpUpdateView,TimelineView,OppTimelineView
)

app_name = "leads"

urlpatterns = [
    path('', LeadListView.as_view(), name='lead-list'),
    path('json/', LeadJsonView.as_view(), name='lead-list-json'),
    path('<int:pk>/', LeadDetailView.as_view(), name='lead-detail'),
    path('<int:pk>/update/', LeadUpdateView.as_view(), name='lead-update'),
    path('<int:pk>/delete/', LeadDeleteView.as_view(), name='lead-delete'),
    path('<int:pk>/assign-agent/', AssignAgentView.as_view(), name='assign-agent'),
    path('<int:pk>/category/', LeadCategoryUpdateView.as_view(), name='lead-category-update'),
    path('<int:pk>/followups/create/', FollowUpCreateView.as_view(), name='lead-followup-create'),
    path('followups/<int:pk>/', FollowUpUpdateView.as_view(), name='lead-followup-update'),
    path('followups/<int:pk>/delete/', FollowUpDeleteView.as_view(), name='lead-followup-delete'),
    path('create/', LeadCreateView.as_view(), name='lead-create'),
    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('categories/<int:pk>/', CategoryDetailView.as_view(), name='category-detail'),
    path('categories/<int:pk>/update/', CategoryUpdateView.as_view(), name='category-update'),
    path('categories/<int:pk>/delete/', CategoryDeleteView.as_view(), name='category-delete'),
    path('create-category/', CategoryCreateView.as_view(), name='category-create'),
    path('opportunities/', OpportunityListView.as_view(), name='opportunity-list'),
    path('<int:pk>/opportunities/convert/', OpportunityConvertView.as_view(), name='opportunity-convert'),
    path('opportunities/<int:pk>/update/', OpportunityUpdateView.as_view(), name='opportunity-update'),
    path('opportunities/<int:pk>/', OpportunityDetailView.as_view(), name='opportunity-detail'),
    path('opportunities/<int:pk>/followups/create/', OppFollowUpCreateView.as_view(), name='opportunity-followup-create'),
    path('opportunities/followups/<int:pk>/', OppFollowUpUpdateView.as_view(), name='opportunity-followup-update'),
    path('<int:pk>/timeline', TimelineView.as_view(), name='timeline'),
    path('opportunities/<int:pk>/timeline', OppTimelineView.as_view(), name='opportunity-timeline'),



]

parties/urls.py
from django.urls import path
from .views import (
    PartyListView, PartyDetailView, PartyCreateView, PartyUpdateView, PartyDeleteView,
    AssignAgentView, PartyJsonView
)

app_name = "parties"

urlpatterns = [
    path('', PartyListView.as_view(), name='party-list'),
    path('json/', PartyJsonView.as_view(), name='party-list-json'),
    path('<int:pk>/', PartyDetailView.as_view(), name='party-detail'),
    path('<int:pk>/update/', PartyUpdateView.as_view(), name='party-update'),
    path('<int:pk>/delete/', PartyDeleteView.as_view(), name='party-delete'),
    path('<int:pk>/assign-agent/', AssignAgentView.as_view(), name='assign-agent'),
    path('create/', PartyCreateView.as_view(), name='party-create'),
]

tasks/urls.py
from django.urls import path
from . import views
from .views import (
    TaskCreateView,
    TaskListView,
    TaskDetailView,
    TaskUpdateView,
    TaskDeleteView,
    OppTaskCreateView,
    TaskNotificationView
)

app_name = "tasks"

urlpatterns = [
    path('', TaskListView.as_view(), name='task-list'),
    path('<int:pk>/create/', TaskCreateView.as_view(), name='task-create'),
    path('accept_invite/<int:task_id>/<str:token>/', TaskCreateView.accept_invite, name='accept-invite'),
    path('<int:pk>/', TaskDetailView.as_view(), name='task-detail'),
    path('<int:pk>/update/', TaskUpdateView.as_view(), name='task-update'),
    # path('opportunity/<int:pk>/delete/', TaskDeleteView.as_view(), name='task-delete'),
    path('opportunity/<int:pk>/create/', OppTaskCreateView.as_view(), name='opportunity-task-create'),
    # path('opportunity/<int:pk>/update/', TaskUpdateView.as_view(), name='task-update'),
    # path('opportunity/<int:pk>/delete/', TaskDeleteView.as_view(), name='task-delete'),
    path('<int:pk>/delete/', TaskDeleteView.as_view(), name='task-delete'),
    path('notification/', TaskNotificationView.as_view(), name='task-notification'),

]

leads/views.py
import logging
import datetime
from typing import Any, Dict
from django import contrib
from django.contrib import messages
from django.core.mail import send_mail
from django.http.response import JsonResponse
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.views import generic
from agents.mixins import OrganizerAndLoginRequiredMixin
from .models import Lead, Agent, Category, FollowUp, Parties ,Opportunities,UserProfile
from .forms import (
    LeadForm, 
    LeadModelForm, 
    CustomUserCreationForm, 
    AssignAgentForm, 
    LeadCategoryUpdateForm,
    CategoryModelForm,
    FollowUpModelForm,
    OpportunityModelForm,
    OpportunityUpdateModelForm
)
from django.db.models import Q


logger = logging.getLogger(__name__)


# CRUD+L - Create, Retrieve, Update and Delete + List

class SignupView(generic.CreateView):
    template_name = "registration/signup.html"
    form_class = CustomUserCreationForm

    def get_success_url(self):
        return reverse("login")

class LandingPageView(generic.TemplateView):
    template_name = "landing.html"

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            if request.user.is_agent:
                return redirect("leads:lead-list")
            elif request.user.is_organizer:
                return redirect("dashboard")

        return super().dispatch(request, *args, **kwargs)


class DashboardView(LoginRequiredMixin, generic.TemplateView):

    template_name = "dashboard.html"

    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)

        user = self.request.user

        if user.is_organizer:
            queryset = Lead.objects.filter(
                organization=user.userprofile, 
                agent__isnull=False
            )
        else:
            queryset = Lead.objects.filter(
                organization=user.agent.organization, 
                agent__isnull=False
            )

        # How many leads we have in total
        total_lead_count = queryset.filter(organization=user.userprofile).count()

        # How many new leads in the last 30 days
        thirty_days_ago = datetime.date.today() - datetime.timedelta(days=30)

        total_in_past30 = queryset.filter(
            organization=user.userprofile,
            created_date__gte=thirty_days_ago
        ).count()

        # How many converted leads in the last 30 days
        converted_category = Category.objects.get(name="Converted", organization=user.userprofile)
        converted_in_past30 = queryset.filter(
            organization=user.userprofile,
            status=converted_category,
            converted_date__gte=thirty_days_ago
        ).count()

        all_categories = []
        
        for i in Category.objects.all():
            all_categories.append(str(i))
            category_count = Category.objects.get(name=i, organization=user.userprofile)
            category_count.count = queryset.filter(status__name__exact=i).count()
            category_count.save()

        context.update({
            "total_lead_count": total_lead_count,
            "total_in_past30": total_in_past30,
            "converted_in_past30": converted_in_past30,
            "qs": Category.objects.filter(organization__exact=user.userprofile)
        })
        return context
 

class LeadListView(LoginRequiredMixin, generic.ListView):
    template_name = "leads/lead_list.html"
    context_object_name = "leads"

    def get_queryset(self):
        user = self.request.user
        # initial queryset of leads for the entire organization
        if user.is_organizer:
            queryset = Lead.objects.filter(
                organization=user.userprofile, 
                agent__isnull=False
            )
        else:
            queryset = Lead.objects.filter(
                organization=user.agent.organization, 
                agent__isnull=False
            )
            # filter for the agent that is logged in
            queryset = queryset.filter(agent__user=user)
            
        return queryset

    def get_context_data(self, **kwargs):
        context = super(LeadListView, self).get_context_data(**kwargs)
        user = self.request.user
        if user.is_organizer:
            queryset = Lead.objects.filter(
                organization=user.userprofile, 
                agent__isnull=True
            )
            context.update({
                "unassigned_leads": queryset
            })
        return context



class LeadDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "leads/lead_detail.html"
    context_object_name = "lead"

    def get_queryset(self):
        user = self.request.user
        # initial queryset of leads for the entire organization
        if user.is_organizer:
            queryset = Lead.objects.filter(organization=user.userprofile)
        else:
            queryset = Lead.objects.filter(organization=user.agent.organization)
            # filter for the agent that is logged in
            queryset = queryset.filter(agent__user=user)
        return queryset


class LeadCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = "leads/lead_create.html"
    form_class = LeadModelForm
    
    def get_success_url(self):
        return reverse("leads:lead-list")
    
    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        user = self.request.user

        # Agent.objects.filter(user=user)[0].organization

        if user.is_organizer:
            form.fields['status'].queryset = Category.objects.filter(
            organization=user.userprofile
            )
            form.fields['agent'].queryset = Agent.objects.filter(
                organization=user.userprofile
            )
            form.fields['party'].queryset = Parties.objects.filter(
                organization=user.userprofile
            )
        
        else:
            organization = Agent.objects.filter(user=user)[0].organization

            form.fields['status'].queryset = Category.objects.filter(
            organization=organization
            )
            form.fields['agent'].queryset = Agent.objects.filter(
                user=user
            )
            form.fields['party'].queryset = Parties.objects.filter(
                organization=organization
            ).filter(Q(agent=Agent.objects.filter(user=user)[0]) | Q(agent=None))
            
        return form

    def form_valid(self, form):
        lead = form.save(commit=False)

        if not self.request.user.is_organizer:
            lead.organization = Agent.objects.filter(user=self.request.user)[0].organization
            lead.agent = Agent.objects.filter(
                user=self.request.user
            )[0]
        
        else:
            lead.organization = self.request.user.userprofile

        lead.save()
        send_mail(
            subject="A lead has been created",
            message="Go to the site to see the new lead",
            from_email="test@test.com",
            recipient_list=["test2@test.com"]
        )
        messages.success(self.request, "You have successfully created a lead")
        return super(LeadCreateView, self).form_valid(form)

class LeadUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name = "leads/lead_update.html"
    form_class = LeadModelForm

    def get_queryset(self):
        user = self.request.user
        # initial queryset of leads for the entire organization
        if user.is_organizer:
            return Lead.objects.filter(organization=user.userprofile)
        else:
            return Lead.objects.filter(organization=Agent.objects.filter(user=user)[0].organization)

    def get_success_url(self):
        return reverse("leads:lead-list")

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        user = self.request.user
        
        if user.is_organizer:
            form.fields['status'].queryset = Category.objects.filter(
            organization=user.userprofile
            )
            form.fields['agent'].queryset = Agent.objects.filter(
                organization=user.userprofile
            )
            form.fields['party'].queryset = Parties.objects.filter(
                organization=user.userprofile
            )
        
        else:
            organization = Agent.objects.filter(user=user)[0].organization

            form.fields['status'].queryset = Category.objects.filter(
            organization=organization
            )
            form.fields['agent'].queryset = Agent.objects.filter(
                user=user
            )
            form.fields['party'].queryset = Parties.objects.filter(
                organization=organization
            ).filter(Q(agent=Agent.objects.filter(user=user)[0]) | Q(agent=None))

        return form

    def form_valid(self, form):
        lead_before_update = self.get_object()
        instance = form.save(commit=False)
        messages.info(self.request, "You have successfully updated this lead")
        if lead_before_update.last_updated_date != datetime.datetime.now():
                # this lead has now been converted
                instance.last_updated_date = datetime.datetime.now()
        instance.save()
        return super(LeadUpdateView, self).form_valid(form)


class LeadDeleteView(OrganizerAndLoginRequiredMixin, generic.DeleteView):
    template_name = "leads/lead_delete.html"

    def get_success_url(self):
        return reverse("leads:lead-list")

    def get_queryset(self):
        user = self.request.user
        # initial queryset of leads for the entire organization
        return Lead.objects.filter(organization=user.userprofile)

class AssignAgentView(OrganizerAndLoginRequiredMixin, generic.FormView):

leads/templates/leads/category_delete.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-lg mx-auto">
    <a class="hover:text-blue-500" href="{% url 'leads:category-list' %}">Go back to categories</a>
    <div class="py-5 border-t border-gray-200">
        <h1 class="text-4xl text-gray-800">Are you sure you want to delete {{ object.name }}?</h1>
    </div>
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
            Delete
        </button>
        <div class="py-5 mt-5">
            <a class="hover:text-blue-500" href="{% url 'leads:category-detail' object.pk %}">Cancel</a>
        </div>
    </form>
</div>

{% endblock content %}

leads/templates/leads/lead_detail.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <div class="w-full flex items-center justify-between space-x-6">
                    <div class="flex-1 truncate">
                        <div class="flex items-center space-x-3">
                            <h3 class="text-3xl text-gray-900 font-medium truncate">{{ lead.name }}</h3>
                        </div>
                        <p class="mt-1 text-xl text-gray-500 truncate">{{ lead.description }}</p>
                    </div>
                    {% if lead.profile_picture %}
                    <img class="w-10 h-10 bg-gray-300 rounded-full flex-shrink-0" src="{{ lead.profile_picture.url }}" alt="">
                    {% endif %}
                </div>
                <div class="flex mb-4">
                    <a href="{% url 'leads:lead-detail' lead.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                        Overview
                    </a>
                    <a href="{% url 'leads:lead-category-update' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                        Status
                    </a>
                    <a href="{% url 'leads:lead-update' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                        Update Details
                    </a>    
                </div>

                <div class="flex border-t border-gray-300 py-2">
                    <span class="text-gray-500">Party</span>
                    <span class="ml-auto text-gray-900">{{ lead.party }}</span>
                </div>

                <div class="flex border-t border-gray-300 py-2">
                    <span class="text-gray-500">Description</span>
                    <span class="ml-auto text-gray-900">{{ lead.description }}</span>
                </div>

                <div class="flex border-t border-gray-300 py-2">
                    <span class="text-gray-500">Status</span>
                    <span class="ml-auto text-gray-900">{{ lead.status }}</span>
                </div>

                <div class="flex border-t border-b mb-6 border-gray-300 py-2">
                    <span class="text-gray-500">Agent</span>
                    <span class="ml-auto text-gray-900">{{ lead.agent }}</span>
                </div>
                
            </div>
        <span>

        <a href="{% url 'leads:lead-followup-create' lead.pk %}" class="text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Add a followup</a>

        <a href="{% url 'tasks:task-create' lead.pk %}" class="text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Add Task</a>
    
        <a href="{% url 'leads:timeline' lead.pk %}" class="text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Timeline</a>

        </span>
        </div>

        {% for followup in lead.followups.all %}
            <div class="mt-5 shadow px-4 sm:px-6">
                <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4">
                    <dt class="text-sm font-medium text-gray-500">
                    Notes (<a href="{% url 'leads:lead-followup-update' followup.pk %}" class="text-blue-500 hover:text-blue-700">update</a>)
                    </dt>
                    <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                    {{ followup.notes }}
                    </dd>
                </div>
                {% if followup.file %}
                    <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4">
                        <dt class="text-sm font-medium text-gray-500">
                        Attachments
                        </dt>
                        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                        <ul class="border border-gray-200 rounded-md divide-y divide-gray-200">
                            <li class="pl-3 pr-4 py-3 flex items-center justify-between text-sm">
                                <div class="w-0 flex-1 flex items-center">
                                    <!-- Heroicon name: paper-clip -->
                                    <svg class="flex-shrink-0 h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                                    <path fill-rule="evenodd" d="M8 4a3 3 0 00-3 3v4a5 5 0 0010 0V7a1 1 0 112 0v4a7 7 0 11-14 0V7a5 5 0 0110 0v4a3 3 0 11-6 0V7a1 1 0 012 0v4a1 1 0 102 0V7a3 3 0 00-3-3z" clip-rule="evenodd" />
                                    </svg>
                                    <span class="ml-2 flex-1 w-0 truncate">
                                    {{ followup.file.name }}
                                    </span>
                                </div>
                                <div class="ml-4 flex-shrink-0">
                                    <a href="{{ followup.file.url }}" download class="font-medium text-indigo-600 hover:text-indigo-500">
                                    Download
                                    </a>
                                </div>
                            </li>
                        </ul>
                        </dd>
                    </div>
                {% endif %}
            </div>
        {% endfor %}


        

    </div>
  </section>
<style>

    .mr-2 {
    margin-left: 30px; 
}
</style>

{% endblock content %}

leads/templates/leads/lead_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ lead.name }}</h1>
            <div class="flex mb-4">
                <a href="{% url 'leads:lead-detail' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Overview
                </a>
                <a href="{% url 'leads:lead-category-update' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Status
                </a>
                <a href="{% url 'leads:lead-update' lead.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                    Update Details
                </a>
            </div>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
            </form>
            <div class="mt-5 py-5 border-t border-gray-200">
                <a href="{% url 'leads:lead-delete' lead.pk %}" class="w-1/2 mt-3 text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                    Delete
                </a>
            </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

leads/templates/leads/opportunity_detail.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <div class="w-full flex items-center justify-between space-x-6">
                    <div class="flex-1 truncate">
                        <div class="flex items-center space-x-3">
                            <h3 class="text-3xl text-gray-900 font-medium truncate">{{ opportunity.name }}</h3>
                        </div>
                        <p class="mt-1 text-xl text-gray-500 truncate">{{ opportunity.description }}</p>
                    </div>
                    {% if lead.profile_picture %}
                    <img class="w-10 h-10 bg-gray-300 rounded-full flex-shrink-0" src="{{ opportunity.profile_picture.url }}" alt="">
                    {% endif %}
                </div>
                <div class="flex mb-4">
                    <a href="{% url 'leads:opportunity-detail' opportunity.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                        Overview
                    </a>
                    <a href="{% url 'leads:opportunity-update' opportunity.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                        Update Details
                    </a>    
                </div>

                <div class="flex border-t border-gray-300 py-2">
                    <span class="text-gray-500">Party</span>
                    <span class="ml-auto text-gray-900">{{ opportunity.party }}</span>
                </div>

                <div class="flex border-t border-gray-300 py-2">
                    <span class="text-gray-500">Description</span>
                    <span class="ml-auto text-gray-900">{{ opportunity.description }}</span>
                </div>

                <div class="flex border-t border-gray-300 py-2">
                    <span class="text-gray-500">Status</span>
                    <span class="ml-auto text-gray-900">{{ opportunity.status }}</span>
                </div>

                <div class="flex border-t border-b mb-6 border-gray-300 py-2">
                    <span class="text-gray-500">Agent</span>
                    <span class="ml-auto text-gray-900">{{ opportunity.agent }}</span>
                </div>
                
            </div>
        <span>

        <a href="{% url 'leads:opportunity-followup-create' opportunity.pk %}" class="text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Add a followup</a>

    
        

        <a href="{% url 'tasks:opportunity-task-create' opportunity.pk %}" class="text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Add Task</a>
    
        <a href="{% url 'leads:opportunity-timeline' opportunity.pk %}" class="text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Timeline</a>

        </span>
            
        </div>

        {% for followup in opportunity.followups_opp.all %}
            <div class="mt-5 shadow px-4 sm:px-6">
                <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4">
                    <dt class="text-sm font-medium text-gray-500">
                    Notes (<a href="{% url 'leads:opportunity-followup-update' followup.pk %}" class="text-blue-500 hover:text-blue-700">update</a>)
                    </dt>
                    <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                    {{ followup.notes }}
                    </dd>
                </div>
                {% if followup.file %}
                    <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4">
                        <dt class="text-sm font-medium text-gray-500">
                        Attachments
                        </dt>
                        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                        <ul class="border border-gray-200 rounded-md divide-y divide-gray-200">
                            <li class="pl-3 pr-4 py-3 flex items-center justify-between text-sm">
                                <div class="w-0 flex-1 flex items-center">
                                    <!-- Heroicon name: paper-clip -->
                                    <svg class="flex-shrink-0 h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                                    <path fill-rule="evenodd" d="M8 4a3 3 0 00-3 3v4a5 5 0 0010 0V7a1 1 0 112 0v4a7 7 0 11-14 0V7a5 5 0 0110 0v4a3 3 0 11-6 0V7a1 1 0 012 0v4a1 1 0 102 0V7a3 3 0 00-3-3z" clip-rule="evenodd" />
                                    </svg>
                                    <span class="ml-2 flex-1 w-0 truncate">
                                    {{ followup.file.name }}
                                    </span>
                                </div>
                                <div class="ml-4 flex-shrink-0">
                                    <a href="{{ followup.file.url }}" download class="font-medium text-indigo-600 hover:text-indigo-500">
                                    Download
                                    </a>
                                </div>
                            </li>
                        </ul>
                        </dd>
                    </div>
                {% endif %}
            </div>
        {% endfor %}
        

    </div>
  </section>
{% endblock content %}