crm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView, 
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.urls import path, include
from leads.views import LandingPageView, SignupView, DashboardView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('leads/',  include('leads.urls', namespace="leads")),
    path('agents/',  include('agents.urls', namespace="agents")),
    path('parties/',  include('parties.urls', namespace="parties")),
    path('tasks/',  include('tasks.urls', namespace="tasks")),
    path('kpis/',  include('kpis.urls', namespace="kpis")),
    path('signup/', SignupView.as_view(), name='signup'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kpis/urls.py
from django.urls import path
from .views import (
    KpiListView, KpiCreateView, KpiUpdateView, TargetCreateView, TargetListView, TargetUpdateView, KpiUpdateViewNew, load_cond2, load_cond1, load_cond_op, load_list_contents, load_targets, load_agents
)

app_name = "kpis"

urlpatterns = [
    path('', KpiListView.as_view(), name='kpi-list'),
    path('create-kpi', KpiCreateView.as_view(), name='kpi-create'),
    # path('<int:pk>/update', KpiUpdateView.as_view(), name='kpi-update'),
    path('<int:pk>/update', KpiUpdateViewNew.as_view(), name='kpi-update'),
    path('list-targets', TargetListView.as_view(), name='target-list'),
    path('create-target', TargetCreateView.as_view(), name='target-create'),
    path('target/<int:pk>/update/', TargetUpdateView.as_view(), name='target-update'),

    path('ajax/load-cond2/', load_cond2, name='ajax_load_cond2'),
    path('ajax/load-cond1/', load_cond1, name='ajax_load_cond1'),
    path('ajax/load-agents/', load_agents, name='ajax_load_agents'),
    path('ajax/load-cond-op/', load_cond_op, name='ajax_load_cond_op'),
    path('ajax/load-list-contents/', load_list_contents, name='ajax_load_list_contents'),
    path('ajax/load-targets/', load_targets, name='ajax_load_targets')
]

kpis/models.py
from django.db import models

# Create your models here.

kpis/forms.py
from django import forms
from leads.models import (KPI, LeadSource, Opportunities, Targets, UserProfile, Condition1, ConditionOperator, Condition2, Module, RecordSelection, Recipient)
from django.db.models import ForeignKey

def get_fk_model(model, fieldname):
    """Returns None if not foreignkey, otherswise the relevant model"""
    field_object, model, direct, m2m = model._meta.get_field_by_name(fieldname)
    if not m2m and direct and isinstance(field_object, ForeignKey):
        return field_object.rel.to
    return None

class RestrictedConditionInput():
    None

class KpiForm(forms.Form):
    name =  forms.CharField(max_length=100)
    module = forms.ModelChoiceField(queryset=Module.objects.all())
    record_selection = forms.ModelChoiceField(queryset=RecordSelection.objects.all())
    points_val_select = forms.BooleanField(label="Set custom value", required=False)
    points_valueOfField = forms.BooleanField(label="Use value of the field as points", required=False)
    points_per_record = forms.IntegerField(label="Set points per record", required=False)
    # recipient = forms.ModelChoiceField(queryset=Recipient.objects.all())
    condition1 = forms.ChoiceField(label="Condition", required=False)
    conditionOp = forms.ChoiceField(label="", required= False)
    condition2 = forms.ChoiceField(label="", required=False)
    condition2int = forms.IntegerField(label="", required=False)

class KpiModelForm(forms.ModelForm):
    # condition2 = None

    class Meta:
        model = KPI 
        fields = [
            "name",
            "module",
            "record_selection",
            "points_per_record",
            "recipient",
            "condition1",
            "conditionOp",
            "condition2"
        ]
        widgets = {
            "condition2": forms.Select(),
            "points_valueOfField": forms.CheckboxInput()
        }

    def clean(self):
        pass

    def __init__(self, *args, **kwargs):
        user=kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        self.fields['condition1'].queryset = Condition1.objects.none()
        self.fields['condition2'].queryset = Condition2.objects.none()
        self.fields['condition1'].label = "Condition"
        self.fields['conditionOp'].label = ""
        self.fields['condition2'].label = ""

class TargetModelForm(forms.ModelForm):
    class Meta:
        model = Targets
        fields = (
            'name',
            'related_kpi',
            'target_points',
            'time_period',
            'for_org',
            'agents'
            # 'organization'
        )
        widgets = {
            "for_org": forms.CheckboxInput(),
            'agents': forms.CheckboxSelectMultiple()
        }

    def clean_first_name(self):
        data = self.cleaned_data["name"]
        return data

    # def clean(self):
    #     pass

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        user_var = self.user
        super(TargetModelForm, self).__init__(*args, **kwargs)
        self.fields['for_org'].label = "for entire organization?"
        agent_queryset = UserProfile.objects.filter(
            user__is_agent = True
        ).filter(user__agent__organization=user_var.userprofile)
        self.fields['agents'].queryset = agent_queryset
        # if self.user.is_organizer:
        #     # form.fields['agents'].queryset = UserProfile.objects.filter(
        #     #     user__is_agent = True
        #     # ).filter(user__agent__organization=user.userprofile)
        #     self.fields['related_kpi'].queryset = KPI.objects.filter(
        #         organization=self.user.userprofile
        #     )
        #     for thing in self.fields['agents'].queryset:
        #         print(thing.user.is_agent)
        #         print(thing.user.username)
        # else:
        #     self.fields['agents'].queryset = UserProfile.objects.filter(
        #         user=self.user
        #     )
        #     self.fields['related_kpi'].queryset = KPI.objects.filter(
        #         organization= self.user.agent.organization
        #     )

kpis/views.py
import json
from typing import Any, Dict
from django.shortcuts import render, reverse
from django.contrib import messages
from django.contrib.auth.mixins import UserPassesTestMixin
from django.template.loader import render_to_string
import datetime
from django.views import generic
from leads.models import KPI, Targets, Lead, LeadSource, Agent, UserProfile, Module, Condition1, Condition2, ConditionOperator, Opportunities, User
from django.forms.models import BaseModelForm, model_to_dict
from .forms import (
    KpiModelForm,
    KpiForm,
    TargetModelForm
)
from django.db.models import ForeignKey
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect, JsonResponse
from django.apps import apps

def get_foreign(model, field_name):
    if field_name == "---------" or field_name == None:
        return None
    field = model._meta.get_field(field_name)
    field_type = type(field)
    is_foreign = str(field_type) == "<class 'django.db.models.fields.related.ForeignKey'>"
    if is_foreign:
        return field.remote_field.model
    else:
        return None


# ---------

def load_list_contents(request):
    period = int(request.GET.get("period"))
    agent_id = int(request.GET.get("agent"))
    is_agent = False

    if agent_id == -1:
        agent = None
    else:
        agent = Agent.objects.get(pk=agent_id)
    
    if request.user.is_agent:
        agent = Agent.objects.get(user=request.user)
        is_agent = True
    else:
        if agent_id == -1:
            agent = None
        else:
            agent = Agent.objects.get(pk=agent_id)

    if request.user.is_organizer:
        organization = request.user.userprofile
    else:
        organization = request.user.agent.organization
    
    cutoff = datetime.date.today() - datetime.timedelta(days=period)

    kpis = KPI.objects.filter(organization = organization)
    queryset = []
    for kpi in kpis:
        module = eval(kpi.module.option)
        if kpi.record_selection.option == "created":
            record_select = "created_date__gte"
        elif kpi.record_selection.option == "modified":
            record_select = "last_updated_date__gte"
        elif kpi.record_selection.option == "converted":
            record_select = "converted_date__gte"
        if kpi.condition1 != None:
            og_field = field = str(kpi.condition1)

            if str(kpi.conditionOp) == "is":
                model = get_foreign(module, field)
                if model == None:
                    field_val = kpi.condition2
                else:
                    field_val = model.objects.get(pk=kpi.condition2)
            else:
                field_val = kpi.condition2
                if str(kpi.conditionOp) == "greater than or equal to":
                    field = field + "__gte"
                elif str(kpi.conditionOp) == "lower than or equal to":
                    field = field + "__lte"
            if agent == None:
                objects = module.objects.filter(**{field: field_val, record_select: cutoff})
            else:
                objects = module.objects.filter(**{field: field_val, record_select: cutoff, 'agent': agent})
        else:
            if agent == None:
                objects = module.objects.filter(**{record_select: cutoff})
            else:
                objects = module.objects.filter(**{record_select: cutoff, 'agent': agent})
        if kpi.points_valueOfField:
            value = 0
            for obj in objects:
                value += getattr(obj, og_field)
        else:
            value = objects.count() * kpi.points_per_record
        print(objects)
        dic = model_to_dict(kpi)
        dic['value'] = value
        # if value != 0:
        queryset.append(dic)

    # return render(request, 'kpis/kpi_list_contents.html', {"kpis": queryset})
    return JsonResponse({"h": render_to_string(request=request, template_name='kpis/kpi_list_contents.html', context={"kpis": queryset, "is_agent": is_agent}), "is_agent": is_agent})


# def load_targets(request):
#     agent_id = int(request.GET.get("agent"))
#     is_agent = False
    
#     if request.user.is_agent:
#         agent = UserProfile.objects.get(user=request.user)
#         is_agent = True
#     else:
#         if agent_id == -1:
#             agent = None
#         else:
#             agent = UserProfile.objects.get(user=Agent.objects.get(pk=agent_id).user)
    
#     if request.user.is_organizer:
#         organization = request.user.userprofile
#     else:
#         organization = request.user.agent.organization
    
#     if agent == None:
#         targets = Targets.objects.filter(organization = organization)
#     else:
#         targets = Targets.objects.filter(organization = organization, agents = agent) | Targets.objects.filter(organization = organization, for_org = True)
    
#     queryset = []
#     for target in targets:
#         kpi = target.related_kpi
#         period_str = target.time_period
#         period = 0
#         if period_str == "Daily":
#             period = 1
#         elif period_str == "Weekly":
#             period = 7
#         elif period_str == "Monthly":
#             period = 30
#         elif period_str == "Yearly":
#             period = 365
#         cutoff = datetime.date.today() - datetime.timedelta(days=period)
#         module = eval(kpi.module.option)
#         if kpi.record_selection.option == "created":
#             record_select = "created_date__gte"
#         elif kpi.record_selection.option == "modified":
#             record_select = "last_updated_date__gte"
#         elif kpi.record_selection.option == "converted":
#             record_select = "converted_date__gte"
#         if kpi.condition1 != None:
#             og_field = field = str(kpi.condition1)
            
#             if str(kpi.conditionOp) == "is":
#                 model = get_foreign(module, field)
#                 if model == None:
#                     field_val = kpi.condition2
#                 else:
#                     field_val = model.objects.get(pk=kpi.condition2)
#             else:
#                 field_val = kpi.condition2
#                 if str(kpi.conditionOp) == "greater than or equal to":
#                     field = field + "__gte"
#                 elif str(kpi.conditionOp) == "lower than or equal to":
#                     field = field + "__lte"
#             if agent == None:
#                 objects = module.objects.filter(**{field: field_val, record_select: cutoff})
#             else:
#                 objects = module.objects.filter(**{field: field_val, record_select: cutoff, 'agent': Agent.objects.get(user=agent.user)})
#         else:
#             if agent == None:
#                 objects = module.objects.filter(**{record_select: cutoff})
#             else:
#                 objects = module.objects.filter(**{record_select: cutoff, 'agent': Agent.objects.get(user=agent.user)})
#         if kpi.points_valueOfField:
#             value = 0
#             for obj in objects:
#                 value += getattr(obj, og_field)
#         else:
#             value = objects.count() * kpi.points_per_record
#         dic = model_to_dict(target)
#         dic['score'] = value
#         # if value != 0:
#         queryset.append(dic)
#     print(queryset)
#     print(is_agent)
    
#     # return render(request, 'kpis/target_list_contents.html', {"targets": queryset, "is_agent": is_agent})
#     return JsonResponse({"h": render_to_string(request=request, template_name='kpis/target_list_contents.html', context={"targets": queryset, "is_agent": is_agent}), "is_agent": is_agent})

def load_targets(request):
    agent_id = int(request.GET.get("agent"))
    is_agent = False
    
    if request.user.is_agent:
        agent = UserProfile.objects.get(user=request.user)
        is_agent = True
    else:
        if agent_id == -1:
            agent = None
        else:
            agent = UserProfile.objects.get(user=Agent.objects.get(pk=agent_id).user)
    
    if request.user.is_organizer:
        organization = request.user.userprofile
    else:
        organization = request.user.agent.organization
    
    if agent == None:
        targets = Targets.objects.filter(organization = organization)
    else:
        targets = Targets.objects.filter(organization = organization, agents = agent) | Targets.objects.filter(organization = organization, for_org = True)
    
    queryset = []
    for target in targets:
        if target.for_org:
            agents_profiles = UserProfile.objects.filter(
                user__is_agent = True
            ).filter(user__agent__organization=organization)
        else:
            agents_profiles = target.agents.all()
        agents = []
        for profile in agents_profiles:
            agents.append(Agent.objects.get(user=profile.user))
        # print(agents_profiles)
        # print(agent)
        if agent != None and (agent not in agents_profiles):
            continue
        kpi = target.related_kpi
        period_str = target.time_period
        period = 0
        if period_str == "Daily":
            period = 1
        elif period_str == "Weekly":
            period = 7
        elif period_str == "Monthly":
            period = 30
        elif period_str == "Yearly":
            period = 365
        cutoff = datetime.date.today() - datetime.timedelta(days=period)
        module = eval(kpi.module.option)
        if kpi.record_selection.option == "created":
            record_select = "created_date__gte"
        elif kpi.record_selection.option == "modified":
            record_select = "last_updated_date__gte"
        elif kpi.record_selection.option == "converted":
            record_select = "converted_date__gte"
        if kpi.condition1 != None:
            og_field = field = str(kpi.condition1)
            
            if str(kpi.conditionOp) == "is":
                model = get_foreign(module, field)
                if model == None:

kpis/templates/kpis/kpi_create.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-lg mx-auto">

    <div class="py-5 border-b border-gray-200">
        <a class="hover:text-blue-500" href="{% url 'kpis:kpi-list' %}">Go back to KPIs</a>
    </div>

    <h1 class="text-4xl text-gray-800">Create a new KPI</h1>
    <form method="post" id="kpiForm" data-url="{% url 'kpis:ajax_load_cond2' %}" module-url="{% url 'kpis:ajax_load_cond1' %}" op-url="{% url 'kpis:ajax_load_cond_op' %}" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
    </form>

</div>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $('#kpiForm').on('submit', function() {
      if ($("[name='condition1']").val() == null || $("[name='condition1']").val() === "") {
        return true;
      }
      if ($("[name='conditionOp']").val() == null || $("[name='conditionOp']").val() === "") {
        alert("Missing codition operator");
        return false;
      }
      if (!($("[name='condition2']").prop('disabled'))) {
        if ($("[name='condition2']").val() == null || $("[name='condition2']").val() === "") {
          alert("Missing condition value");
          return false;
        } else {
          return true;
        }
      }
      if (!($("[name='condition2int']").prop('disabled'))) {
        if ($("[name='condition2int']").val() == null || $("[name='condition2int']").val() === "") {
          return false;
          alert("Missing condition value");
        } else {
          return true;
        }
      }
      alert("Condition incomplete");
      return false;
    });
    console.log($("[name='condition1']").val());
    $("[id='div_id_condition2']").hide()
    $("[id='div_id_condition2int']").hide()
    $("[id='div_id_points_per_record']").show();
    $("[name='points_valueOfField']").prop('checked', false);
    $("[name='points_valueOfField']").prop('disabled', 'disabled');
    $("[name='points_val_select']").prop('checked', true);
    $("[id='div_id_conditionOp']").hide();
    function change_valueOfField() {
      if ($("[name='points_valueOfField']").is(":checked")) {
        $("[name='points_per_record']").prop('disabled', 'disabled');
        $("[id='div_id_points_per_record']").hide();
        $("[name='points_val_select']").prop('checked', false);
      } else {
        $("[name='points_val_select']").prop('checked', true);
        $("[name='points_valueOfField']").prop('checked', false);
        $("[id='div_id_points_per_record']").show();
        $("[name='points_per_record']").prop('disabled', false);
      }
    }
    function change_val_select() {
      if ($("[name='points_val_select']").is(":checked")){
        $("[name='points_valueOfField']").prop('checked', false);
        $("[id='div_id_points_per_record']").show();
        $("[name='points_per_record']").prop('disabled', false);
      } else {
        $("[name='points_valueOfField']").prop('checked', true);
        $("[id='div_id_points_per_record']").hide();
      }
    }
    $("[name='points_valueOfField']").change(change_valueOfField);
    $("[name='points_val_select']").change(change_val_select);
    $("[name='module']").change(function () {
      var url = $("#kpiForm").attr("module-url");
      var moduleId = $(this).find("option:selected").text();
    
      $.ajax({
        url: url,
        data: {
          'module': moduleId
        },
        success: function (data) {
          $("[name='condition1']").html(data);
        }
      });

    });
    $("[name='condition1']").change(function () {
      var url = $("#kpiForm").attr("data-url");
      var opUrl = $("#kpiForm").attr("op-url");
      var fieldId = $(this).find("option:selected").text();
      //console.log($("[name='condition1']").val());
    
      $.ajax({
        url: opUrl,
        data: {
          'field': fieldId,
          'module': $("[name='module']").find("option:selected").text()
        },
        success: function (data) {
          $("[name='conditionOp']").html(data.h);
          if (data.foreign) {
            $("[name='condition2']").prop('disabled', false);
            $("[id='div_id_condition2']").show();
            $("[name='condition2int']").prop('disabled', 'disabled');
            $("[id='div_id_condition2int']").hide();
            $("[name='points_val_select']").prop('checked', true);
            $("[name='points_valueOfField']").prop('disabled', true);
            $("[name='points_val_select']").prop('disabled', true);
            if ($("[name='condition1']").val() == null || $("[name='condition1']").val() === "") {
              console.log($("[name='condition1']").val());
              $("[name='condition1']").prop('required', false);
              $("[name='conditionOp']").prop('required', false);
              $("[name='condition2']").prop('required', false);
              $("[name='condition2int']").prop('required', false);
              $("[id='div_id_condition2']").hide();
              $("[id='div_id_condition2int']").hide();
              $("[id='div_id_conditionOp']").hide();
            } else {
              $("[name='condition1']").prop('required', true);
              $("[name='conditionOp']").prop('required', true);
              $("[name='condition2']").prop('required', true);
              $("[name='condition2int']").prop('required', false);
              $("[id='div_id_conditionOp']").show();
            }
            change_val_select()
          } else {
            $("[name='condition2']").prop('disabled', 'disabled');
            $("[id='div_id_condition2']").hide();
            $("[name='condition2int']").prop('disabled', false);
            $("[id='div_id_condition2int']").show();
            $("[name='points_valueOfField']").prop('disabled', false);
            $("[name='points_val_select']").prop('disabled', false);
            if ($("[name='condition1']").val() == null || $("[name='condition1']").val() === "") {
              $("[name='condition1']").prop('required', false);
              $("[name='conditionOp']").prop('required', false);
              $("[name='condition2']").prop('required', false);
              $("[name='condition2int']").prop('required', false);
              $("[id='div_id_condition2']").hide();
              $("[id='div_id_condition2int']").hide();
              $("[id='div_id_conditionOp']").hide();
            } else {
              $("[name='condition1']").prop('required', true);
              $("[name='conditionOp']").prop('required', true);
              $("[name='condition2']").prop('required', false);
              $("[name='condition2int']").prop('required', true);
              $("[id='div_id_conditionOp']").show();
            }
          }
        }
      });

      $.ajax({
        url: url,
        data: {
          'field': fieldId,
          'module': $("[name='module']").find("option:selected").text()
        },
        success: function (data) {
          $("[name='condition2']").html(data);
        }
      });

    });
    $("[name='condition2']").change(function () {
        console.log($(this).find("option:selected").text());
        console.log($(this).val());
      });
  </script>

{% endblock content %}

kpis/templates/kpis/kpi_dropdown_agents.html
<option value=-1>Organization</option>
{% for agent in agents %}
<option value="{{ agent.id }}">{{ agent.str }}</option>
{% endfor %}

kpis/templates/kpis/kpi_dropdown_cond2.html
<option value="">---------</option>
{% for field_val in field_vals %}
<option value="{{ field_val.id }}">{{ field_val.str }}</option>
{% endfor %}

kpis/templates/kpis/kpi_list.html
{% extends "base.html" %}

{% block content %}
    <section class="text-gray-700 body-font">
        <div class="container px-5 py-24 mx-auto flex flex-wrap">
            <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
                <div>
                    <h1 class="text-4xl text-gray-800">KPIs</h1>
                </div>
                <div>
                    <select id="selectPeriod" data-url="{% url 'kpis:ajax_load_list_contents' %}">
                        <option value=7>Weekly</option>
                        <option value=30>Monthly</option>
                        <option value=365>Yearly</option>
                    </select>
                </div>
                <div>
                    <select id="selectAgent" data-url="{% url 'kpis:ajax_load_agents' %}">
                        <option value=-1>Organization</option>
                    </select>
                </div>
                <div>
                    <a class="text-gray-500 hover:text-blue-500" href="{% url 'kpis:kpi-create' %}">Create a new KPI</a>
                </div>
            </div>

            <div id="list-contents" class="flex flex-col w-full">
                <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                    <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                    <table class="min-w-full divide-y divide-gray-200">
                        <thead class="bg-gray-50">
                            <tr>
                                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Name
                                </th>
                                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Value
                                </th>
                                <th scope="col" class="relative px-6 py-3">
                                <span class="sr-only">Edit</span>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for kpi in kpis %}
                                <tr class="bg-white">
                                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                        {{ kpi.name }}
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                        {{ kpi.value }}
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                        <a href="{% url 'kpis:kpi-update' kpi.pk %}" class="text-indigo-600 hover:text-indigo-900">
                                            Edit
                                        </a>
                                    </td>
                                </tr>
                            {% empty %}

                            <p>There are currently no KPIs</p>

                            {% endfor %}
                        </tbody>
                    </table>
                    </div>
                </div>
                </div>
            </div>

        </div>
      </section>

      <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

      <script>
        function get_list() {
            var url = $("#selectPeriod").attr("data-url");
            var fieldId = $(this).find("option:selected").text();
            var period = document.getElementById('selectPeriod').value
            var agent = document.getElementById('selectAgent').value
            $.ajax({
              url: url,
              data: {
                'period': period,
                'agent': agent
              },
              success: function (data) {
                $("#list-contents").html(data.h);
                if (data.is_agent) {
                  $('#selectAgent').hide()
                }
              }
            });
        }
        function get_agents() {
            var url = $("#selectAgent").attr("data-url");
            $.ajax({
              url: url,
              data: {},
              success: function (data) {
                $("#selectAgent").html(data);
              }
            });
        }
        get_agents();
        get_list();
        $("#selectPeriod").change(get_list);
        $("#selectAgent").change(get_list);
      </script>
{% endblock content %}

kpis/templates/kpis/target_list.html
{% extends "base.html" %}

{% block content %}
<section class="text-gray-700 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
      <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
          <div>
              <h1 class="text-4xl text-gray-800">Targets</h1>
          </div>
          <div>
              <select id="selectAgent" data-url="{% url 'kpis:ajax_load_agents' %}">
                  <option value=-1>Organization</option>
              </select>
          </div>
          <div>
              <a class="text-gray-500 hover:text-blue-500" href="{% url 'kpis:target-create' %}">Create a new Target</a>
          </div>
      </div>

      <div id="list-contents" data-url="{% url 'kpis:ajax_load_targets' %}" class="flex flex-col w-full">
      </div>
      </div>
      <div id="error-message" class="text-red-500"></div>
  </div>

</div>
</section>

      <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

      <script>
        function get_list() {
            var url = $("#list-contents").attr("data-url");
            var agent = document.getElementById('selectAgent').value
            $.ajax({
              url: url,
              data: {'agent': agent},
              success: function (data) {
                $("#list-contents").html(data.h);
                if (data.is_agent) {
                  $('#selectAgent').css("height", 0);
                }
              },
              error: function (xhr, status, error) {
                $("#error-message").text("Error fetching target data: " + error);
            }
            });
        }
        function get_agents() {
            var url = $("#selectAgent").attr("data-url");
            $.ajax({
              url: url,
              data: {},
              success: function (data) {
                $("#selectAgent").html(data);
              }
            });
        }
        get_agents();
        get_list();
        $("#selectAgent").change(get_list);
      </script>
      
{% endblock content %}