agents/urls.py
from django.urls import path
from .views import (
    AgentListView, AgentCreateView, AgentDetailView, 
    AgentUpdateView, AgentDeleteView
)

app_name = 'agents'

urlpatterns = [
    path('', AgentListView.as_view(), name='agent-list'),
    path('<int:pk>/', AgentDetailView.as_view(), name='agent-detail'),
    path('<int:pk>/update/', AgentUpdateView.as_view(), name='agent-update'),
    path('<int:pk>/delete/', AgentDeleteView.as_view(), name='agent-delete'),
    path('create/', AgentCreateView.as_view(), name='agent-create'),
    
]

crm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView, 
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.urls import path, include
from leads.views import LandingPageView, SignupView, DashboardView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('leads/',  include('leads.urls', namespace="leads")),
    path('agents/',  include('agents.urls', namespace="agents")),
    path('parties/',  include('parties.urls', namespace="parties")),
    path('tasks/',  include('tasks.urls', namespace="tasks")),
    path('kpis/',  include('kpis.urls', namespace="kpis")),
    path('signup/', SignupView.as_view(), name='signup'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kpis/urls.py
from django.urls import path
from .views import (
    KpiListView, KpiCreateView, KpiUpdateView, TargetCreateView, TargetListView, TargetUpdateView, KpiUpdateViewNew, load_cond2, load_cond1, load_cond_op, load_list_contents, load_targets, load_agents
)

app_name = "kpis"

urlpatterns = [
    path('', KpiListView.as_view(), name='kpi-list'),
    path('create-kpi', KpiCreateView.as_view(), name='kpi-create'),
    # path('<int:pk>/update', KpiUpdateView.as_view(), name='kpi-update'),
    path('<int:pk>/update', KpiUpdateViewNew.as_view(), name='kpi-update'),
    path('list-targets', TargetListView.as_view(), name='target-list'),
    path('create-target', TargetCreateView.as_view(), name='target-create'),
    path('target/<int:pk>/update/', TargetUpdateView.as_view(), name='target-update'),

    path('ajax/load-cond2/', load_cond2, name='ajax_load_cond2'),
    path('ajax/load-cond1/', load_cond1, name='ajax_load_cond1'),
    path('ajax/load-agents/', load_agents, name='ajax_load_agents'),
    path('ajax/load-cond-op/', load_cond_op, name='ajax_load_cond_op'),
    path('ajax/load-list-contents/', load_list_contents, name='ajax_load_list_contents'),
    path('ajax/load-targets/', load_targets, name='ajax_load_targets')
]

leads/urls.py
from django.urls import path
from .views import (
    LeadListView, LeadDetailView, LeadCreateView, LeadUpdateView, LeadDeleteView,
    AssignAgentView, CategoryListView, CategoryDetailView, LeadCategoryUpdateView,
    CategoryCreateView, CategoryUpdateView, CategoryDeleteView, LeadJsonView, 
    FollowUpCreateView, FollowUpUpdateView, FollowUpDeleteView, OpportunityListView, OpportunityConvertView,
    OpportunityUpdateView,OpportunityDetailView,OppFollowUpCreateView,OppFollowUpUpdateView,TimelineView,OppTimelineView
)

app_name = "leads"

urlpatterns = [
    path('', LeadListView.as_view(), name='lead-list'),
    path('json/', LeadJsonView.as_view(), name='lead-list-json'),
    path('<int:pk>/', LeadDetailView.as_view(), name='lead-detail'),
    path('<int:pk>/update/', LeadUpdateView.as_view(), name='lead-update'),
    path('<int:pk>/delete/', LeadDeleteView.as_view(), name='lead-delete'),
    path('<int:pk>/assign-agent/', AssignAgentView.as_view(), name='assign-agent'),
    path('<int:pk>/category/', LeadCategoryUpdateView.as_view(), name='lead-category-update'),
    path('<int:pk>/followups/create/', FollowUpCreateView.as_view(), name='lead-followup-create'),
    path('followups/<int:pk>/', FollowUpUpdateView.as_view(), name='lead-followup-update'),
    path('followups/<int:pk>/delete/', FollowUpDeleteView.as_view(), name='lead-followup-delete'),
    path('create/', LeadCreateView.as_view(), name='lead-create'),
    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('categories/<int:pk>/', CategoryDetailView.as_view(), name='category-detail'),
    path('categories/<int:pk>/update/', CategoryUpdateView.as_view(), name='category-update'),
    path('categories/<int:pk>/delete/', CategoryDeleteView.as_view(), name='category-delete'),
    path('create-category/', CategoryCreateView.as_view(), name='category-create'),
    path('opportunities/', OpportunityListView.as_view(), name='opportunity-list'),
    path('<int:pk>/opportunities/convert/', OpportunityConvertView.as_view(), name='opportunity-convert'),
    path('opportunities/<int:pk>/update/', OpportunityUpdateView.as_view(), name='opportunity-update'),
    path('opportunities/<int:pk>/', OpportunityDetailView.as_view(), name='opportunity-detail'),
    path('opportunities/<int:pk>/followups/create/', OppFollowUpCreateView.as_view(), name='opportunity-followup-create'),
    path('opportunities/followups/<int:pk>/', OppFollowUpUpdateView.as_view(), name='opportunity-followup-update'),
    path('<int:pk>/timeline', TimelineView.as_view(), name='timeline'),
    path('opportunities/<int:pk>/timeline', OppTimelineView.as_view(), name='opportunity-timeline'),



]

tasks/urls.py
from django.urls import path
from . import views
from .views import (
    TaskCreateView,
    TaskListView,
    TaskDetailView,
    TaskUpdateView,
    TaskDeleteView,
    OppTaskCreateView,
    TaskNotificationView
)

app_name = "tasks"

urlpatterns = [
    path('', TaskListView.as_view(), name='task-list'),
    path('<int:pk>/create/', TaskCreateView.as_view(), name='task-create'),
    path('accept_invite/<int:task_id>/<str:token>/', TaskCreateView.accept_invite, name='accept-invite'),
    path('<int:pk>/', TaskDetailView.as_view(), name='task-detail'),
    path('<int:pk>/update/', TaskUpdateView.as_view(), name='task-update'),
    # path('opportunity/<int:pk>/delete/', TaskDeleteView.as_view(), name='task-delete'),
    path('opportunity/<int:pk>/create/', OppTaskCreateView.as_view(), name='opportunity-task-create'),
    # path('opportunity/<int:pk>/update/', TaskUpdateView.as_view(), name='task-update'),
    # path('opportunity/<int:pk>/delete/', TaskDeleteView.as_view(), name='task-delete'),
    path('<int:pk>/delete/', TaskDeleteView.as_view(), name='task-delete'),
    path('notification/', TaskNotificationView.as_view(), name='task-notification'),

]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Al Yousuf Group - CRM</title>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    <link rel="shortcut icon" type="image/png" href="{% static 'crm/images/favicon.ico' %}"/>
  </head>
  <body>
    <div class="max-w-7xl mx-auto">
      {% include 'navbar.html' %} 
      {% include 'messages.html' %} 
      {% block content %} 
      {% endblock content %}
    </div>
    {% include "scripts.html" %}
  </body>
</html>

templates/crispy_custom.html
{% load crispy_forms_tags %}

{% block crispy_forms_field %}
{% spaceless %}
    <div class="form-group{% if field.errors %} has-error{% endif %}">
        {% if field.label %}
            <label for="{{ field.id_for_label }}" class="control-label{% if field.field.required %} requiredField{% endif %}">
                {% include 'crispy_forms/field_label.html' %}
            </label>
        {% endif %}

        <div class="controls">
            {% include 'crispy_forms/field.html' %}
            {% include 'crispy_forms/help_text_and_errors.html' %}
        </div>
    </div>
{% endspaceless %}
{% endblock crispy_forms_field %}

templates/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="text-gray-700 body-font">
    <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
      <div class="text-center lg:w-2/3 w-full">
        <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">
            Al Yousuf CRM Dashboard
        </h1>
    
        <div class="mt-5 flex flex-wrap -m-4 text-center">
            <div class="p-4 md:w-1/3 sm:w-1/2 w-full">
                <div class="border-2 border-gray-200 px-4 py-6 rounded-lg">
                <h2 class="title-font font-medium text-3xl text-gray-900">{{ total_lead_count }}</h2>
                <p class="leading-relaxed">Total Leads</p>
                </div>
            </div>
            <div class="p-4 md:w-1/3 sm:w-1/2 w-full">
                <div class="border-2 border-gray-200 px-4 py-6 rounded-lg">
                <h2 class="title-font font-medium text-3xl text-gray-900">{{ total_in_past30 }}</h2>
                <p class="leading-relaxed">Leads added in last 30 days</p>
                </div>
            </div>
            <div class="p-4 md:w-1/3 sm:w-1/2 w-full">
                <div class="border-2 border-gray-200 px-4 py-6 rounded-lg">
                <h2 class="title-font font-medium text-3xl text-gray-900">{{ converted_in_past30 }}</h2>
                <p class="leading-relaxed">Converted in last 30 days</p>
                </div>
            </div>
        </div>

        <div class="mt-5">
            <canvas id="myChart" width="450" height="200"></canvas>  
        <div>    

    </div>

</section>

        <!--Chart js-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" integrity="sha256-Uv9BNBucvCPipKQ2NS9wYpJmi8DTOEfTA/nH2aoJALw=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css" integrity="sha256-aa0xaJgmK/X74WM224KMQeNQC2xYKwlAt08oZqjeF0E=" crossorigin="anonymous" />
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

    <script>


$(document).ready(function(){
        var ctx = document.getElementById('myChart').getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'doughnut',
            data: {
                labels: [{%for data in qs%}'{{data.name}}',{%endfor%}],
                datasets: [{
                    label: 'Number of users',
                    data: [{%for data in qs%}{{data.count}},{%endfor%}],
                    backgroundColor: [
                        'rgba(255, 206, 86, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(255, 99, 132, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)'
                    ],
                    borderColor: [
                        'rgba(255, 206, 86, 1.8)',
                        'rgba(54, 162, 235, 1.8)',
                        'rgba(75, 192, 192, 1.8)',
                        'rgba(255, 99, 132, 1.8)',
                        'rgba(153, 102, 255, 1.8)',
                        'rgba(255, 159, 64, 1.8)'
                    ],
                    borderWidth: 0
                }]
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
});
    });
</script>


{% endblock content %}

templates/landing.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="text-gray-700 body-font">
    <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
    <center>
      <video width="720" height="1280" controls autoplay muted>
        <source src="{% static "crm/images/video.mp4" %}" type="video/mp4">
      </video>
    </center>
      <div class="mt-5 text-center lg:w-2/3 w-full">
        <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">
            Built by Suhail Ahmed
        </h1>
        <p class="mb-4 leading-relaxed">
            Part of the Al Yousuf Internship - 2023
        </p>
        <div class="flex justify-center">
          <a href="{% url 'login' %}" class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">
            Login to get started
          </a>
        </div>
      </div>
    </div>
</section>
{% endblock content %}

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="p-4 border-l-4
        {% if message.tags == 'success' %}
        bg-green-50 border-green-400
        {% elif message.tags == 'info' %}
        bg-blue-50 border-blue-400
        {% elif message.tags == 'warning' %}
        bg-yellow-50 border-yellow-400
        {% else %}
        bg-red-50 border-red-400
        {% endif %}
        ">
            <p class="text-sm
            {% if message.tags == 'success' %}
            text-green-700
            {% elif message.tags == 'info' %}
            text-blue-700
            {% elif message.tags == 'warning' %}
            text-yellow-700
            {% else %}
            text-red-700
            {% endif %}
            ">
                {{ message }}
            </p>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<header class="text-gray-700 body-font">
  <div
    class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center"
  >

  {% if request.user.is_organizer %}

    <a
      href="{% url 'dashboard' %}"
      class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0"
    >
      {% load static %} <img class="w-10 h-10" src="{% static "crm/images/logo.png" %}" alt="Logo" />
      <span class="ml-3 text-xl">Al Yousuf Group</span>
    </a>

  {% else %}
    
    {% load static %} <img class="w-10 h-10" src="{% static "crm/images/logo.png" %}" alt="Logo" />
    <span class="ml-3 text-xl">Al Yousuf Group</span>
  
  {% endif %}


    <nav
      class="md:ml-auto flex flex-wrap items-center text-base justify-center"
    >
      {% if not request.user.is_authenticated %}
      <a href="{% url 'signup' %}" class="mr-5 hover:text-gray-900">Signup</a>
      {% else %} 
      {% if request.user.is_organizer %}
      <a href="{% url 'agents:agent-list' %}" class="mr-5 hover:text-gray-900"
        >Agents</a>
      <a href="{% url 'kpis:kpi-list' %}" class="mr-5 hover:text-gray-900"
        >KPIs</a>
      
      {% endif %}
      <a href="{% url 'leads:lead-list' %}" class="mr-5 hover:text-gray-900"
        >Leads</a
      >
      <a href="{% url 'parties:party-list' %}" class="mr-5 hover:text-gray-900"
        >Parties</a
      >
      <a href="{% url 'tasks:task-list' %}" class="mr-5 hover:text-gray-900"
        >Tasks</a
      >
      <a href="{% url 'leads:opportunity-list' %}" class="mr-5 hover:text-gray-900"
      >Opportunities</a>
      
      <a href="{% url 'kpis:target-list' %}" class="mr-5 hover:text-gray-900"
      >Targets</a>
      <a href="{% url 'tasks:task-notification' %}" class="mr-5 hover:text-gray-900"
      >Notifications</a>
      
        <!-- <img
            src="/static/crm/images/icons8-notification-50.png"
            alt="Notification Icon"
            class="w-8 h-8 text-gray-500 hover:text-blue-500 ml-2"
        />
        </a> -->

      {% endif %}
    </nav>
    {% if request.user.is_authenticated %} Logged in as:
    {{request.user.username}}
    <a
      href="{% url 'logout' %}"
      class="ml-3 inline-flex items-center bg-gray-200 border-0 py-1 px-3 focus:outline-none hover:bg-gray-300 rounded text-base mt-4 md:mt-0"
    >
      Logout
      <svg
        fill="none"
        stroke="currentColor"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
        class="w-4 h-4 ml-1"
        viewBox="0 0 24 24"
      >
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    </a>
    {% else %}
    <a
      href="{% url 'login' %}"
      class="inline-flex items-center bg-gray-200 border-0 py-1 px-3 focus:outline-none hover:bg-gray-300 rounded text-base mt-4 md:mt-0"
    >
      Login
      <svg
        fill="none"
        stroke="currentColor"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
        class="w-4 h-4 ml-1"
        viewBox="0 0 24 24"
      >
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    </a>
    {% endif %}
  </div>
</header>

templates/scripts.html
{% load static %}

<script src="{% static 'js/main.js' %}"></script>