crm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView, 
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.urls import path, include
from leads.views import LandingPageView, SignupView, DashboardView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('leads/',  include('leads.urls', namespace="leads")),
    path('agents/',  include('agents.urls', namespace="agents")),
    path('parties/',  include('parties.urls', namespace="parties")),
    path('tasks/',  include('tasks.urls', namespace="tasks")),
    path('kpis/',  include('kpis.urls', namespace="kpis")),
    path('signup/', SignupView.as_view(), name='signup'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leads/urls.py
from django.urls import path
from .views import (
    LeadListView, LeadDetailView, LeadCreateView, LeadUpdateView, LeadDeleteView,
    AssignAgentView, CategoryListView, CategoryDetailView, LeadCategoryUpdateView,
    CategoryCreateView, CategoryUpdateView, CategoryDeleteView, LeadJsonView, 
    FollowUpCreateView, FollowUpUpdateView, FollowUpDeleteView, OpportunityListView, OpportunityConvertView,
    OpportunityUpdateView,OpportunityDetailView,OppFollowUpCreateView,OppFollowUpUpdateView,TimelineView,OppTimelineView
)

app_name = "leads"

urlpatterns = [
    path('', LeadListView.as_view(), name='lead-list'),
    path('json/', LeadJsonView.as_view(), name='lead-list-json'),
    path('<int:pk>/', LeadDetailView.as_view(), name='lead-detail'),
    path('<int:pk>/update/', LeadUpdateView.as_view(), name='lead-update'),
    path('<int:pk>/delete/', LeadDeleteView.as_view(), name='lead-delete'),
    path('<int:pk>/assign-agent/', AssignAgentView.as_view(), name='assign-agent'),
    path('<int:pk>/category/', LeadCategoryUpdateView.as_view(), name='lead-category-update'),
    path('<int:pk>/followups/create/', FollowUpCreateView.as_view(), name='lead-followup-create'),
    path('followups/<int:pk>/', FollowUpUpdateView.as_view(), name='lead-followup-update'),
    path('followups/<int:pk>/delete/', FollowUpDeleteView.as_view(), name='lead-followup-delete'),
    path('create/', LeadCreateView.as_view(), name='lead-create'),
    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('categories/<int:pk>/', CategoryDetailView.as_view(), name='category-detail'),
    path('categories/<int:pk>/update/', CategoryUpdateView.as_view(), name='category-update'),
    path('categories/<int:pk>/delete/', CategoryDeleteView.as_view(), name='category-delete'),
    path('create-category/', CategoryCreateView.as_view(), name='category-create'),
    path('opportunities/', OpportunityListView.as_view(), name='opportunity-list'),
    path('<int:pk>/opportunities/convert/', OpportunityConvertView.as_view(), name='opportunity-convert'),
    path('opportunities/<int:pk>/update/', OpportunityUpdateView.as_view(), name='opportunity-update'),
    path('opportunities/<int:pk>/', OpportunityDetailView.as_view(), name='opportunity-detail'),
    path('opportunities/<int:pk>/followups/create/', OppFollowUpCreateView.as_view(), name='opportunity-followup-create'),
    path('opportunities/followups/<int:pk>/', OppFollowUpUpdateView.as_view(), name='opportunity-followup-update'),
    path('<int:pk>/timeline', TimelineView.as_view(), name='timeline'),
    path('opportunities/<int:pk>/timeline', OppTimelineView.as_view(), name='opportunity-timeline'),



]

parties/urls.py
from django.urls import path
from .views import (
    PartyListView, PartyDetailView, PartyCreateView, PartyUpdateView, PartyDeleteView,
    AssignAgentView, PartyJsonView
)

app_name = "parties"

urlpatterns = [
    path('', PartyListView.as_view(), name='party-list'),
    path('json/', PartyJsonView.as_view(), name='party-list-json'),
    path('<int:pk>/', PartyDetailView.as_view(), name='party-detail'),
    path('<int:pk>/update/', PartyUpdateView.as_view(), name='party-update'),
    path('<int:pk>/delete/', PartyDeleteView.as_view(), name='party-delete'),
    path('<int:pk>/assign-agent/', AssignAgentView.as_view(), name='assign-agent'),
    path('create/', PartyCreateView.as_view(), name='party-create'),
]

parties/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField
from leads.models import Lead, Agent, Category, FollowUp, Parties

User = get_user_model()


class PartyModelForm(forms.ModelForm):
    class Meta:
        model = Parties
        fields = (
            'first_name',
            'last_name',
            'user_type',
            'primary_number',
            'whatsapp_number',
            'email',
            'preferred_contact_method',
            'agent'
        )

    def clean_first_name(self):
        data = self.cleaned_data["first_name"]
        # if data != "Joe":
        #     raise ValidationError("Your name is not Joe")
        return data

    def clean(self):
        pass
        # first_name = self.cleaned_data["first_name"]
        # last_name = self.cleaned_data["last_name"]
        # if first_name + last_name != "Joe Soap":
        #     raise ValidationError("Your name is not Joe Soap")



class AssignAgentForm(forms.Form):
    agent = forms.ModelChoiceField(queryset=Agent.objects.none())

    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request")
        agents = Agent.objects.filter(organization=request.user.userprofile)
        super(AssignAgentForm, self).__init__(*args, **kwargs)
        self.fields["agent"].queryset = agents

parties/views.py
import logging
import datetime
from django import contrib
from django.contrib import messages
from django.core.mail import send_mail
from django.http.response import JsonResponse
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.views import generic
from agents.mixins import OrganizerAndLoginRequiredMixin
from leads.models import Parties, Agent, Category
from .forms import (
    PartyModelForm, 
    AssignAgentForm, 
)


logger = logging.getLogger(__name__)


# CRUD+L - Create, Retrieve, Update and Delete + List

class PartyListView(LoginRequiredMixin, generic.ListView):
    template_name = "parties/party_list.html"
    context_object_name = "parties"

    def get_queryset(self):
        user = self.request.user
        # initial queryset of leads for the entire organization
        if user.is_organizer:
            queryset = Parties.objects.filter(
                organization=user.userprofile, 
                agent__isnull=False
            )
        else:
            queryset = Parties.objects.filter(
                organization=user.agent.organization, 
                agent__isnull=False
            )
            # filter for the agent that is logged in
            queryset = queryset.filter(agent__user=user)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(PartyListView, self).get_context_data(**kwargs)
        user = self.request.user
        if user.is_organizer:
            queryset = Parties.objects.filter(
                organization=user.userprofile, 
                agent__isnull=True
            )
            context.update({
                "unassigned_parties": queryset
            })
        return context

class PartyDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "parties/party_detail.html"
    context_object_name = "party"

    def get_queryset(self):
        user = self.request.user
        # initial queryset of leads for the entire organization
        if user.is_organizer:
            queryset = Parties.objects.filter(organization=user.userprofile)
        else:
            queryset = Parties.objects.filter(organization=user.agent.organization)
            # filter for the agent that is logged in
            queryset = queryset.filter(agent__user=user)
        return queryset

class PartyCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = "parties/party_create.html"
    form_class = PartyModelForm

    def get_success_url(self):
        return reverse("parties:party-list")
    
    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        user = self.request.user
        if user.is_organizer:
            form.fields['agent'].queryset = Agent.objects.filter(
            organization=user.userprofile
        )   
        else:
            form.fields['agent'].queryset = Agent.objects.filter(user=user)
            
        return form

    def form_valid(self, form):
        party = form.save(commit=False)

        if not self.request.user.is_organizer:
            party.organization = Agent.objects.filter(user=self.request.user)[0].organization
            party.agent = Agent.objects.filter(
                user=self.request.user
            )[0]
        
        else:
            party.organization = self.request.user.userprofile

        party.save()
        send_mail(
            subject="A party has been created",
            message="Go to the site to see the new party",
            from_email="test@test.com",
            recipient_list=["test2@test.com"]
        )
        messages.success(self.request, "You have successfully created a party")
        return super(PartyCreateView, self).form_valid(form)


class PartyUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name = "parties/party_update.html"
    form_class = PartyModelForm
    context_object_name = "party"

    def get_queryset(self):
        user = self.request.user
        # initial queryset of leads for the entire organization
        if user.is_organizer:
            return Parties.objects.filter(organization=user.userprofile)
        else:
            return Parties.objects.filter(organization=Agent.objects.filter(user=user)[0].organization)
    
    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        user = self.request.user
        
        if user.is_organizer:
            form.fields['agent'].queryset = Agent.objects.filter(
            organization=user.userprofile
        )   
        else:
            form.fields['agent'].queryset = Agent.objects.filter(user=user)

        return form

    def get_success_url(self):
        return reverse("parties:party-list")

    def form_valid(self, form):
        party_before_update = self.get_object()
        instance = form.save(commit=False)

        if not self.request.user.is_organizer:
            instance.agent = Agent.objects.filter(
                user=self.request.user
            )[0]
        

        messages.info(self.request, "You have successfully updated this party")
        if party_before_update.last_updated_date != datetime.datetime.now():
                # this lead has now been converted
                instance.last_updated_date = datetime.datetime.now()
        instance.save()
        return super(PartyUpdateView, self).form_valid(form)



class PartyDeleteView(OrganizerAndLoginRequiredMixin, generic.DeleteView):
    template_name = "parties/party_delete.html"

    def get_success_url(self):
        return reverse("parties:party-list")

    def get_queryset(self):
        user = self.request.user
        # initial queryset of parties for the entire organization
        return Parties.objects.filter(organization=user.userprofile)
    

class AssignAgentView(OrganizerAndLoginRequiredMixin, generic.FormView):
    template_name = "parties/assign_agent.html"
    form_class = AssignAgentForm

    def get_form_kwargs(self, **kwargs):
        kwargs = super(AssignAgentView, self).get_form_kwargs(**kwargs)
        kwargs.update({
            "request": self.request
        })
        return kwargs
        
    def get_success_url(self):
        return reverse("parties:party-list")

    def form_valid(self, form):
        agent = form.cleaned_data["agent"]
        party = Parties.objects.get(id=self.kwargs["pk"])
        party.agent = agent
        party.save()
        return super(AssignAgentView, self).form_valid(form)

class PartyJsonView(generic.View):

    def get(self, request, *args, **kwargs):
        
        qs = list(Parties.objects.all().values(
            "first_name", 
            "last_name", 
            "primary_number",
            "whatsapp_number",
            "email",
            "preferred_contact_method",
            "organization")
        )

        return JsonResponse({
            "qs": qs,
        })

parties/templates/parties/assign_agent.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-lg mx-auto">
    <a class="hover:text-blue-500" href="{% url 'parties:party-list' %}">Go back to parties</a>
    <div class="py-5 border-t border-gray-200">
        <h1 class="text-4xl text-gray-800">Assign an agent to this party</h1>
    </div>
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
            Submit
        </button>
    </form>
</div>

{% endblock content %}

parties/templates/parties/party_create.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-lg mx-auto">
    <a class="hover:text-blue-500" href="{% url 'parties:party-list' %}">Go back to parties</a>
    <div class="py-5 border-t border-gray-200">
        <h1 class="text-4xl text-gray-800">Create a new party</h1>
    </div>
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
            Submit
        </button>
    </form>
</div>

{% endblock content %}

parties/templates/parties/party_delete.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
<div class="max-w-lg mx-auto">
    <div class="py-5 border-b border-gray-200">
        <a class="hover:text-blue-500" href="{% url 'parties:party-list' %}">Go back to parties</a>
    </div>
    <h1 class="text-3xl text-gray-800">Are you sure you want to delete this party?</h1>
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Delete</button>
        <div class="py-5 mt-5">
            <a class="hover:text-blue-500" href="{% url 'parties:party-detail' object.pk %}">Cancel</a>
        </div>
    </form>
</div>
{% endblock content %}

parties/templates/parties/party_detail.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <div class="w-full flex items-center justify-between space-x-6">
                    <div class="flex-1 truncate">
                        <div class="flex items-center space-x-3">
                            <h3 class="text-3xl text-gray-900 font-medium truncate">{{ party.first_name }} {{ party.last_name }}</h3>
                        </div>
                        <p class="mt-1 text-xl text-gray-500 truncate">{{ party.description }}</p>
                    </div>
                    {% if party.profile_picture %}
                    <img class="w-11 h-20 sm:w-20 sm:h-20 bg-gray-300 rounded-full flex-shrink-0" src="{{ party.profile_picture.url }}" alt="">
                    {% endif %}
                </div>
                <div class="flex mb-4">
                    <a href="{% url 'parties:party-detail' party.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                        Overview
                    </a>
                    <a href="{% url 'parties:party-update' party.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                        Update Details
                    </a>    
                </div>
                <div class="flex border-t border-gray-300 py-2">
                    <span class="text-gray-500">Type</span>
                    <span class="ml-auto text-gray-900">{{ party.user_type }}</span>
                </div>

                <div class="flex border-t border-gray-300 py-2">
                    <span class="text-gray-500">Preferred Contact</span>
                    <span class="ml-auto text-gray-900">{{ party.preferred_contact_method }}</span>
                </div>

                <div class="flex border-t border-gray-300 py-2">
                    <span class="text-gray-500">Primary Number</span>
                    <span class="ml-auto text-gray-900">{{ party.primary_number }}</span>
                </div>

                <div class="flex border-t border-gray-300 py-2">
                    <span class="text-gray-500">WhatsApp Number</span>
                    <span class="ml-auto text-gray-900">{{ party.whatsapp_number }}</span>
                </div>

                <div class="flex border-t border-gray-300 py-2">
                    <span class="text-gray-500">Email</span>
                    <span class="ml-auto text-gray-900">{{ party.email }}</span>
                </div>

                <div class="flex border-t border-b mb-6 border-gray-300 py-2">
                    <span class="text-gray-500">Agent</span>
                    <span class="ml-auto text-gray-900">{{ party.agent }}</span>
                </div>
            </div>
    </div>
  </section>
{% endblock content %}

parties/templates/parties/party_list.html
{% extends "base.html" %} {% block content %}

<section class="text-gray-700 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
    <div
      class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200"
    >
      <div>
        <h1 class="text-4xl text-gray-800">Parties</h1>
        <a
          class="text-gray-500 hover:text-blue-500"
          href="{% url 'leads:category-list' %}"
        >
          View categories
        </a>
      </div>
      {% comment %} {% if request.user.is_organizer %} {% endcomment %}
      <div>
        <a
          class="text-gray-500 hover:text-blue-500"
          href="{% url 'parties:party-create' %}"
        >
          Create a new party
        </a>
      </div>
      {% comment %} {% endif %} {% endcomment %}
    </div>

    <div class="flex flex-col w-full">
      <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
          <div
            class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg"
          >
            <table class="min-w-full divide-y divide-gray-200">
              <thead class="bg-gray-50">
                <tr>
                  <th
                    scope="col"
                    class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                  >
                    Name
                  </th>
                  <th
                    scope="col"
                    class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                  >
                    Type
                  </th>
                  <th
                    scope="col"
                    class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                  >
                    Primary Number
                  </th>
                  <th
                    scope="col"
                    class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                  >
                    WhatsApp Number
                  </th>
                  <th
                    scope="col"
                    class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                  >
                    Email
                  </th>
                  <th
                    scope="col"
                    class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                  >
                    Preferred Contact
                  </th>
                  <th
                    scope="col"
                    class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                  >
                    Agent
                  </th>
                  <th
                    scope="col"
                    class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                  >
                    Party Type
                  </th>
                  <th scope="col" class="relative px-6 py-3">
                    <span class="sr-only">Edit</span>
                  </th>
                </tr>
              </thead>
              <tbody>
                {% for party in parties %}
                <tr class="bg-white">
                  <td
                    class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900"
                  >
                    <a
                      class="text-blue-500 hover:text-blue-800"
                      href="{% url 'parties:party-detail' party.pk %}"
                      >{{ party.first_name }} {{ party.last_name }}</a
                    >
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    {{ party.user_type }}
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    {{ party.primary_number }}
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    {{ party.whatsapp_number }}
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    {{ party.email }}
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    {{ party.preferred_contact_method }}
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    {{ party.agent }}
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    {{ party.user_type }}
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                    <a
                      href="{% url 'parties:party-update' party.pk %}"
                      class="text-indigo-600 hover:text-indigo-900"
                    >
                      Edit
                    </a>
                  </td>
                </tr>

                {% empty %}

                <p class="mb-2">There are currently no parties</p>

                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

    {% if unassigned_parties.exists %}
    <div class="mt-5 flex flex-wrap -m-4">
      <div class="p-4 w-full">
        <h1 class="text-4xl text-gray-800">Unassigned parties</h1>
      </div>
      {% for party in unassigned_parties %}
      <div class="p-4 lg:w-1/2 md:w-full">
        <div
          class="flex border-2 rounded-lg border-gray-200 p-8 sm:flex-row flex-col"
        >
          <div
            class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0"
          >
            <svg
              fill="none"
              stroke="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              class="w-8 h-8"
              viewBox="0 0 24 24"
            >
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
              {{ party.first_name }} {{ party.last_name }}
            </h2>
            <p class="leading-relaxed text-base">{{ party.description }}</p>
            <a
              href="{% url 'parties:assign-agent' party.pk %}"
              class="mt-3 text-indigo-500 inline-flex items-center"
            >
              Assign an agent
              <svg
                fill="none"
                stroke="currentColor"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                class="w-4 h-4 ml-2"
                viewBox="0 0 24 24"
              >
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    {% endif %}
  </div>
</section>
{% endblock content %}

parties/templates/parties/party_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">PARTY</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ party.first_name }} {{ party.last_name }}</h1>
            <div class="flex mb-4">
                <a href="{% url 'parties:party-detail' party.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Overview
                </a>
                <a href="{% url 'parties:party-update' party.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                    Update Details
                </a>
            </div>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
            </form>
            <div class="mt-5 py-5 border-t border-gray-200">
                <a href="{% url 'parties:party-delete' party.pk %}" class="w-1/2 mt-3 text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                    Delete
                </a>
            </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}